module.exports = {
  genes: [
    { name: 'ABC1' },
    { name: 'ABC2' },
    { name: 'ABRA' },
    { name: 'ABBA' },
    { name: 'LEVI' },
    { name: 'WRNGLR' },
  ],

  variants: [
    {
      id: 1,
      geneId: 1,
      nucleotideChanges: ['NC100', 'NC101'],
      proteinChange: 'p.xxyyxxzz',
      alias: '',
      region: '',
      reportedClassification: 'Good',
      source: 'nick.com',
      lastEvaluated: null,
      lastUpdated: null,
      url: 'www.nick.com',
    },
    {
      id: 2,
      geneId: 1,
      nucleotideChanges: ['NC100', 'NC101'],
      proteinChange: 'p.123123123',
      alias: '',
      region: '',
      reportedClassification: 'Bad',
      source: 'nick.com',
      lastEvaluated: null,
      lastUpdated: null,
      url: 'www.nick.com',
    },
    {
      id: 3,
      geneId: 2,
      nucleotideChanges: ['NC100', 'NC101'],
      proteinChange: 'p.qwertyuiop',
      alias: '',
      region: '',
      reportedClassification: 'Ugly',
      source: 'nick.com',
      lastEvaluated: null,
      lastUpdated: null,
      url: 'www.nick.com',
    },
  ],
};
