// This file is for markup purposes

export default [
  {
    id: 1,
    gene: 'ABC1',
    nucleotideChanges: ['NC100', 'NC101'],
    proteinChange: 'p.xxyyxxzz',
    alias: '',
    region: '',
    reportedClassification: 'Good',
    source: 'nick.com',
    lastEvaluated: null,
    lastUpdated: null,
    url: 'https://www.nick.com',
  },
  {
    id: 2,
    gene: 'ABC1',
    nucleotideChanges: ['NC100', 'NC101'],
    proteinChange: 'p.123123123',
    alias: '',
    region: '',
    reportedClassification: 'Bad',
    source: 'nick.com',
    lastEvaluated: null,
    lastUpdated: null,
    url: 'https://www.nick.com',
  },
  {
    id: 3,
    gene: 'ABC2',
    nucleotideChanges: ['NC100', 'NC101'],
    proteinChange: 'p.qwertyuiop',
    alias: '',
    region: '',
    reportedClassification: 'Ugly',
    source: 'nick.com',
    lastEvaluated: null,
    lastUpdated: null,
    url: 'https://www.nick.com',
  },
];
